# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


s = 2
i_0 = 1
i_1 = 2
buf = 0

while i_1 < 4000000:
        buf = i_1
        i_1 = i_0 + i_1
        i_0 = buf
        if i_1 % 2 == 0:
            s = s + i_1
        print(i_1)

print('Сумма=', s)
print('Сумма=', s)
print('Сумма=', s)
print('Сумма=', s)
print('Сумма=', s)
print('Сумма=', s)
print('Сумма=', s)
print('Сумма=', s)
print('Сумма=', s)
print('Сумма=', s)

print('Сумма=', s)
print('Сумма=', s)
print('Сумма=', s)
print('Сумма=', s)
print('Сумма=', s)
print('Сумма=', s)
print('Сумма=', s)
print('Сумма=', s)
print('Сумма=', s)
print('Сумма=', s)

